# Generated by Django 6.0.2 on 2026-02-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('address_full', models.CharField(blank=True, default='', max_length=512)),
                ('location_reference', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('timezone', models.CharField(default='America/New_York', max_length=100)),
                ('primary_lang', models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('other', 'other')], default='es', max_length=16)),
                ('conversation_tone', models.CharField(choices=[('formal', 'Formal'), ('friendly', 'Friendly'), ('adaptive', 'Adaptive')], default='friendly', max_length=16)),
                ('welcome_phrase', models.TextField(blank=True, default='')),
                ('phone_mode', models.CharField(choices=[('new', 'New number'), ('existing', 'Existing number')], default='new', help_text='existing = keep public number and forward to Twilio; new = use Twilio number as public', max_length=16)),
                ('existing_ph_numb', models.CharField(blank=True, default='', max_length=32)),
                ('twilio_pn_numb', models.CharField(blank=True, default='', max_length=32)),
                ('twilio_in_numb_sid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('forwarding_enabled', models.BooleanField(default=False)),
                ('notify_via_email', models.BooleanField(default=True)),
                ('notify_email', models.EmailField(blank=True, default='', max_length=254)),
                ('notify_via_ws', models.BooleanField(default=False)),
                ('notify_ws_numb', models.CharField(blank=True, default='', max_length=32)),
                ('notify_other', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
