# Generated by Django 6.0.2 on 2026-02-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='retell_agent_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='retell_phone_number_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
