# Generated by Django 6.0.2 on 2026-02-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_retell_agent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='retell_api_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
