# Generated by Django 6.0.2 on 2026-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_retell_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='retell_llm_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
