# Generated by Django 6.0.2 on 2026-02-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_retell_llm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='retell_voice_id',
            field=models.CharField(blank=True, default='retell-Claudia', max_length=64),
        ),
    ]
