# Generated by Django 6.0.2 on 2026-02-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_retell_voice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='retell_phone_number_id',
            new_name='retell_phone_number',
        ),
    ]
