# Generated by Django 6.0.2 on 2026-02-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_rename_retell_phone_number_id_restaurant_retell_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='twilio_in_numb_sid',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='twilio_pn_numb',
        ),
    ]
