# Generated by Django 6.0.2 on 2026-02-27 05:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_restaurant_twilio_in_numb_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
