# Generated by Django 6.0.2 on 2026-03-02 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_callevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RestaurantKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_of_operation', models.TextField(blank=True, default='')),
                ('kitchen_closing_time', models.CharField(blank=True, default='', max_length=128)),
                ('closes_on_holidays', models.BooleanField(default=False)),
                ('holiday_closure_notes', models.TextField(blank=True, default='')),
                ('private_event_closures', models.TextField(blank=True, default='')),
                ('food_menu_url', models.URLField(blank=True, default='')),
                ('food_menu_summary', models.TextField(blank=True, default='', help_text='~300 word curated summary: best sellers, price range, categories. Used by the AI on calls.')),
                ('bar_menu_url', models.URLField(blank=True, default='')),
                ('bar_menu_summary', models.TextField(blank=True, default='', help_text='Cocktail/wine/beer highlights with prices. Used by the AI on calls.')),
                ('happy_hour_details', models.TextField(blank=True, default='')),
                ('dietary_options', models.TextField(blank=True, default='', help_text='Vegan, gluten-free, nut-free, and other dietary options available.')),
                ('auto_gratuity', models.BooleanField(default=False)),
                ('service_charge_pct', models.CharField(blank=True, default='', max_length=32)),
                ('service_charge_scope', models.CharField(blank=True, choices=[('all', 'All tables'), ('large_parties', 'Large parties only'), ('', 'N/A')], default='', max_length=32)),
                ('max_cards_to_split', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reservation_grace_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('no_show_fee', models.CharField(blank=True, default='', max_length=128)),
                ('large_party_min_guests', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_private_dining', models.BooleanField(default=False)),
                ('private_dining_min_spend', models.CharField(blank=True, default='', max_length=128)),
                ('allows_decorations', models.BooleanField(default=False)),
                ('decoration_cleaning_fee', models.CharField(blank=True, default='', max_length=128)),
                ('press_contact', models.CharField(blank=True, default='', max_length=255)),
                ('has_live_music', models.BooleanField(default=False)),
                ('live_music_details', models.TextField(blank=True, default='')),
                ('party_vibe_start_time', models.CharField(blank=True, default='', max_length=64)),
                ('noise_level', models.CharField(blank=True, choices=[('quiet', 'Quiet'), ('moderate', 'Moderate'), ('loud', 'Loud'), ('very_loud', 'Very Loud')], default='', max_length=16)),
                ('dress_code', models.CharField(blank=True, default='', max_length=255)),
                ('cover_charge', models.CharField(blank=True, default='', max_length=128)),
                ('has_terrace', models.BooleanField(default=False)),
                ('ac_intensity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('strong', 'Strong / Cold')], default='', max_length=16)),
                ('stroller_friendly', models.BooleanField(default=False)),
                ('has_valet', models.BooleanField(default=False)),
                ('valet_cost', models.CharField(blank=True, default='', max_length=64)),
                ('free_parking_info', models.TextField(blank=True, default='')),
                ('collect_guest_info', models.BooleanField(default=True)),
                ('guest_info_to_collect', models.TextField(blank=True, default='name, party size, date, time, phone number')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='restaurants.restaurant')),
            ],
        ),
    ]
