# Generated by Django 6.0.2 on 2026-03-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='art_gallery_info',
            field=models.TextField(blank=True, default='', help_text='Art gallery description and how to inquire about artwork or collaborations.'),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='cigar_policy',
            field=models.CharField(blank=True, default='', help_text='Where cigars are allowed and any special cigar promotions.', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='show_charge_policy',
            field=models.CharField(blank=True, default='', help_text='Show/entertainment charge for large groups (e.g. 15+ guests).', max_length=255),
        ),
    ]
