# Generated by Django 6.0.2 on 2026-03-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_restaurantknowledgebase_art_gallery_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='retell_area_code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Area code for purchasing a Retell phone number (e.g. 786 for Miami).', null=True),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='brand_voice_notes',
            field=models.TextField(blank=True, default='', help_text="Restaurant-specific style, sample phrases, and language notes for the AI agent. Include example responses in the restaurant's preferred language, key brand phrases, and any custom routing instructions unique to this restaurant."),
        ),
    ]
