# Generated by Django 6.0.2 on 2026-03-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_restaurant_retell_area_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='additional_info',
            field=models.TextField(blank=True, default='', help_text="Any additional information the AI agent should know that isn't covered by the fields above. Use this for special policies, FAQs, promotions, or anything unique to your restaurant."),
        ),
    ]
