# Generated by Django 6.0.2 on 2026-03-03 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_restaurantknowledgebase_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(blank=True, default='', max_length=255)),
                ('caller_phone', models.CharField(blank=True, default='', max_length=32)),
                ('caller_email', models.CharField(blank=True, default='', max_length=255)),
                ('call_reason', models.CharField(blank=True, choices=[('reservation', 'Reservation'), ('hours', 'Hours / Schedule'), ('menu', 'Menu / Food'), ('billing', 'Billing / Payment'), ('parking', 'Parking / Valet'), ('private_event', 'Private Event'), ('complaint', 'Complaint'), ('other', 'Other / General')], default='other', max_length=32)),
                ('wants_reservation', models.BooleanField(blank=True, null=True)),
                ('party_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reservation_date', models.CharField(blank=True, default='', max_length=128)),
                ('reservation_time', models.CharField(blank=True, default='', max_length=64)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='restaurants.callevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
