# Generated by Django 6.0.2 on 2026-03-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_calldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='special_events_info',
            field=models.TextField(blank=True, default='', help_text="Upcoming or recurring special events at the restaurant (e.g. themed nights, holiday dinners, live shows, pop-ups). The AI agent will use this to inform callers about what's coming up."),
        ),
    ]
