# Generated by Django 6.0.2 on 2026-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='twilio_account_sid',
            field=models.CharField(blank=True, default='', help_text='Twilio Account SID for this restaurant. Leave blank to use the platform default.', max_length=64),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='twilio_auth_token',
            field=models.CharField(blank=True, default='', help_text='Twilio Auth Token for this restaurant.', max_length=64),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='twilio_from_number',
            field=models.CharField(blank=True, default='', help_text='Twilio phone number to send SMS from (E.164 format, e.g. +17865550000).', max_length=32),
        ),
    ]
