# Generated by Django 6.0.2 on 2026-03-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_restaurant_twilio_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='affiliated_restaurants',
            field=models.TextField(blank=True, default='', help_text='Comma-separated restaurant names the agent may confirm affiliation with. Example: Cuba Ocho, Calle Dragones Colombia. Leave blank to disable affiliation confirmation.'),
        ),
    ]
