# Generated by Django 6.0.2 on 2026-03-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_kb_affiliated_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='escalation_conditions',
            field=models.TextField(blank=True, default='If the caller is physically at or outside the restaurant and it is currently outside working hours.', help_text='Describe when the agent should escalate. The agent monitors for these conditions on every call.'),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='escalation_enabled',
            field=models.BooleanField(default=False, help_text='Allow the agent to transfer the call to a human when escalation conditions are met.'),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='escalation_transfer_number',
            field=models.CharField(blank=True, default='', help_text='Phone number to transfer to (E.164 format, e.g. +17865551234). Leave blank to take a message instead of transferring.', max_length=30),
        ),
    ]
