# Generated by Django 6.0.2 on 2026-03-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_kb_escalation'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='bar_concept',
            field=models.CharField(blank=True, default='', help_text="Bar specialty & concept. e.g. 'Craft cocktails, extensive rum & mezcal selection'.", max_length=200),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='bar_signature_drinks',
            field=models.TextField(blank=True, default='', help_text='Signature cocktails with prices. One drink per line.'),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='bar_wine_beer',
            field=models.TextField(blank=True, default='', help_text="Wine & beer selection highlights. e.g. 'Full wine list, draft beers, bottle service on weekends'."),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='menu_best_sellers',
            field=models.TextField(blank=True, default='', help_text='Best sellers & popular dishes with prices. One item per line.'),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='menu_categories',
            field=models.CharField(blank=True, default='', help_text="Menu sections. e.g. 'Starters, Raw bar, Mains, Desserts, Sharing plates'.", max_length=255),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='menu_cuisine_type',
            field=models.CharField(blank=True, default='', help_text="Cuisine type & concept. e.g. 'Latin-Asian fusion, tapas-style sharing plates'.", max_length=200),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='menu_price_range',
            field=models.CharField(blank=True, default='', help_text="Typical price range. e.g. '$15–$35 per dish' or '$60–$80 per person'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='bar_menu_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='food_menu_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
