# Generated by Django 6.0.2 on 2026-03-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_kb_structured_menu_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='contact_email_spoken',
            field=models.CharField(blank=True, default='', help_text="How the agent should say the email address aloud. Leave blank to auto-generate. Example (ES): 'admon calle dragones arroba gmail punto com' Example (EN): 'admon calle dragones at gmail dot com'", max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='bar_menu_summary',
            field=models.TextField(blank=True, default='', help_text='Cocktail/wine/beer highlights with prices. Used by the AI on calls.'),
        ),
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='bar_signature_drinks',
            field=models.TextField(blank=True, default='', help_text='Signature cocktails with prices. One item per line.'),
        ),
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='bar_wine_beer',
            field=models.TextField(blank=True, default='', help_text='Wine & beer selection highlights.'),
        ),
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='food_menu_summary',
            field=models.TextField(blank=True, default='', help_text='~300 word curated summary: best sellers, price range, categories. Used by the AI on calls.'),
        ),
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='menu_best_sellers',
            field=models.TextField(blank=True, default='', help_text='Signature dishes with prices. One item per line.'),
        ),
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='menu_categories',
            field=models.CharField(blank=True, default='', help_text="Menu sections. e.g. 'Starters, Dumplings, Wok & fried rice, Mains, Sides'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='menu_price_range',
            field=models.CharField(blank=True, default='', help_text="Typical price range. e.g. '$15–$35 per dish'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='private_event_closures',
            field=models.TextField(blank=True, default='', help_text='Dates when the restaurant is fully or partially closed due to private events or buyouts. Use format: Month D, YYYY — description. One entry per line. Example: March 15, 2026: closed for private event.'),
        ),
    ]
