# Generated by Django 6.0.2 on 2026-03-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0025_owner_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='communication_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
