# Generated by Django 6.0.2 on 2026-03-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0026_subscription_communication_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='bar_concept',
            field=models.TextField(blank=True, default='', help_text="Bar specialty & concept. e.g. 'Craft cocktails, extensive rum & mezcal selection'."),
        ),
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='menu_cuisine_type',
            field=models.TextField(blank=True, default='', help_text="Cuisine type & concept. e.g. 'Latin-Asian fusion, tapas-style sharing plates'."),
        ),
    ]
