# Generated by Django 6.0.2 on 2026-03-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0027_fix_bar_concept_cuisine_type_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent (in transit)'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='twilio_sid',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
