# Generated by Django 6.0.2 on 2026-03-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0028_smslog_delivered_at_and_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='reservation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='reservation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
