# Generated by Django 6.0.2 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0029_reservation_date_time_to_proper_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='notify_daily_digest',
            field=models.BooleanField(default=True, help_text="Morning digest email with previous day's call summary."),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notify_on_complaint',
            field=models.BooleanField(default=True, help_text='Urgent email when the AI detects a complaint.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notify_on_followup',
            field=models.BooleanField(default=True, help_text='Email when the AI flags a call as needing a callback.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notify_on_reservation',
            field=models.BooleanField(default=True, help_text='Email the owner when a caller expresses reservation intent.'),
        ),
    ]
