# Generated by Django 6.0.2 on 2026-03-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0030_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='call_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Combined cost of this call in USD (voice + LLM).', max_digits=8, null=True),
        ),
    ]
