# Generated by Django 6.0.2 on 2026-03-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0031_call_cost_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='communication_markup',
            field=models.DecimalField(decimal_places=2, default=1.3, help_text="Multiplier applied to Retell's combined_cost before deducting from balance. e.g. 1.30 = 30% markup. Set to 1.00 for no markup.", max_digits=4),
        ),
    ]
