# Generated by Django 6.0.2 on 2026-03-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0032_communication_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='disclaimer_message',
            field=models.TextField(blank=True, default='Esta llamada puede ser grabada por motivos de calidad.', help_text='Optional. Spoken immediately before the welcome phrase (e.g. for recording consent).'),
        ),
    ]
