# Generated by Django 6.0.2 on 2026-03-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0033_restaurant_disclaimer_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='disclaimer_message',
        ),
    ]
