# Generated by Django 6.0.2 on 2026-03-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0035_pendingemailchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='enable_sms',
            field=models.BooleanField(default=False, help_text='Enable Twilio SMS sending capabilities and the Retell AI SMS tool.'),
        ),
    ]
