# Generated by Django 6.0.2 on 2026-03-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0036_restaurant_enable_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='recording_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
