# Generated by Django 6.0.2 on 2026-03-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0037_calldetail_recording_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='follow_up_needed',
            field=models.BooleanField(default=True),
        ),
    ]
