# Generated by Django 6.0.2 on 2026-03-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0038_alter_calldetail_follow_up_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='avg_revenue_per_cover',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average revenue per guest per visit (e.g. 45.00). Used to estimate ROI on the dashboard.', max_digits=8, null=True),
        ),
    ]
