# Generated by Django 6.0.2 on 2026-03-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0039_avg_revenue_per_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='reservation_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calldetail',
            name='reservation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('lost', 'Lost')], default='pending', help_text='Staff-confirmed outcome for reservation leads.', max_length=16),
        ),
    ]
