# Generated by Django 6.0.2 on 2026-03-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0040_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='call_reason',
            field=models.CharField(blank=True, choices=[('reservation', 'Reservation'), ('hours', 'Hours / Schedule'), ('menu', 'Menu / Food'), ('bar_menu', 'Bar Menu / Drinks'), ('happy_hour', 'Happy Hour'), ('billing', 'Billing / Payment'), ('parking', 'Parking / Valet'), ('private_event', 'Private Event'), ('complaint', 'Complaint'), ('other', 'Other / General')], default='other', max_length=32),
        ),
    ]
