# Generated by Django 6.0.2 on 2026-03-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0042_calldetail_bar_menu_happy_hour_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='caller_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
