# Generated by Django 6.0.2 on 2026-03-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0043_minor_fixes_email_field_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='financial_call_handling',
            field=models.CharField(choices=[('ignore', 'Ignore (handle normally)'), ('message', 'Take a message'), ('transfer', 'Transfer to staff')], default='message', help_text='How to handle calls from banks, collection agencies, or legal firms.', max_length=16),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='partner_call_ask_urgency',
            field=models.BooleanField(default=True, help_text='Before acting, ask the caller if the matter is urgent.'),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='partner_call_handling',
            field=models.CharField(choices=[('ignore', 'Ignore (handle normally)'), ('message', 'Take a message'), ('transfer', 'Transfer to staff')], default='message', help_text='How to handle calls from listed partner companies.', max_length=16),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='partner_companies',
            field=models.TextField(blank=True, default='', help_text='Companies with an active relationship (e.g. DoorDash, OpenTable, Toast). One per line. The agent will recognize callers from these companies.'),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='press_call_ask_urgency',
            field=models.BooleanField(default=False, help_text='Before acting, ask the caller if the matter is urgent.'),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='press_call_handling',
            field=models.CharField(choices=[('ignore', 'Ignore (handle normally)'), ('give_contact', 'Give press contact'), ('message', 'Take a message'), ('transfer', 'Transfer to staff')], default='give_contact', help_text='How to handle calls from press, media, or influencers.', max_length=16),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='sales_call_handling',
            field=models.CharField(choices=[('ignore', 'Ignore (handle normally)'), ('decline', 'Decline politely'), ('message', 'Take a message')], default='decline', help_text='How to handle unsolicited sales or marketing calls.', max_length=16),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='service_call_ask_urgency',
            field=models.BooleanField(default=True, help_text='Before acting, ask the caller if the matter is urgent.'),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='service_call_handling',
            field=models.CharField(choices=[('ignore', 'Ignore (handle normally)'), ('decline', 'Decline politely'), ('message', 'Take a message'), ('transfer', 'Transfer to staff')], default='message', help_text='How to handle calls from external service providers.', max_length=16),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='spam_call_handling',
            field=models.CharField(choices=[('decline', 'Decline politely'), ('end_call', 'End call immediately')], default='end_call', help_text='How to handle automated or spam calls.', max_length=16),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='urgent_call_action',
            field=models.CharField(choices=[('message_urgent', 'Take urgent message'), ('transfer', 'Transfer to staff')], default='message_urgent', help_text='What to do when a non-customer caller confirms their matter is urgent.', max_length=16),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='vendor_call_ask_urgency',
            field=models.BooleanField(default=True, help_text='Before acting, ask the caller if the matter is urgent.'),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='vendor_call_handling',
            field=models.CharField(choices=[('ignore', 'Ignore (handle normally)'), ('decline', 'Decline politely'), ('message', 'Take a message'), ('transfer', 'Transfer to staff')], default='message', help_text='How to handle calls from vendors or suppliers not on the partner list.', max_length=16),
        ),
    ]
