# Generated by Django 6.0.2 on 2026-03-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0044_non_customer_call_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='notify_on_non_customer',
            field=models.BooleanField(default=True, help_text='Email when the AI identifies a non-customer business call (vendor, press, sales, etc.).'),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='call_reason',
            field=models.CharField(blank=True, choices=[('reservation', 'Reservation'), ('hours', 'Hours / Schedule'), ('menu', 'Menu / Food'), ('bar_menu', 'Bar Menu / Drinks'), ('happy_hour', 'Happy Hour'), ('billing', 'Billing / Payment'), ('parking', 'Parking / Valet'), ('private_event', 'Private Event'), ('complaint', 'Complaint'), ('non_customer', 'Non-Customer / Business Call'), ('other', 'Other / General')], default='other', max_length=32),
        ),
    ]
