# Generated by Django 6.0.2 on 2026-03-20 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0045_non_customer_reason_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='call_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CallerMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('last_call_at', models.DateTimeField(blank=True, null=True)),
                ('last_call_summary', models.TextField(blank=True, default='')),
                ('preferences', models.TextField(blank=True, default='', help_text="e.g. 'prefers terrace seating, gluten-free'")),
                ('staff_notes', models.TextField(blank=True, default='', help_text="e.g. 'VIP', 'do not call before noon'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller_memories', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-last_call_at'],
                'unique_together': {('restaurant', 'phone')},
            },
        ),
    ]
