# Generated by Django 6.0.2 on 2026-03-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0046_caller_memory_and_call_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='callermemory',
            name='caller_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('business', 'Business Contact')], db_index=True, default='guest', help_text="'guest' = customer; 'business' = vendor, press, sales, etc.", max_length=16),
        ),
    ]
