# Generated by Django 6.0.2 on 2026-03-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0049_deduplicate_call_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='callermemory',
            name='pending_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
