# Generated by Django 6.0.2 on 2026-03-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0050_pending_name_on_caller_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='team_members',
            field=models.TextField(blank=True, default='', help_text='Staff the agent should recognize by name. One per line, format: Name — Role.'),
        ),
    ]
