# Generated by Django 6.0.2 on 2026-03-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0051_add_team_members_to_kb'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='corkage_policy',
            field=models.TextField(blank=True, default='', help_text='Corkage fee policy — amount, conditions, limits.'),
        ),
    ]
