# Generated by Django 6.0.2 on 2026-03-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0052_add_corkage_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='bottle_service',
            field=models.TextField(blank=True, default='', help_text='Bottle service details — availability, brands, pricing, pre-order policy.'),
        ),
    ]
