# Generated by Django 6.0.2 on 2026-03-27 01:09

from django.db import migrations


def create_owner_memberships(apps, schema_editor):
    Restaurant = apps.get_model("restaurants", "Restaurant")
    Membership = apps.get_model("restaurants", "RestaurantMembership")
    for r in Restaurant.objects.filter(user__isnull=False):
        Membership.objects.get_or_create(
            user=r.user,
            restaurant=r,
            defaults={"role": "owner", "is_active": True, "can_edit_kb": True},
        )


def remove_owner_memberships(apps, schema_editor):
    Membership = apps.get_model("restaurants", "RestaurantMembership")
    Membership.objects.filter(role="owner").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0054_add_restaurant_membership"),
    ]

    operations = [
        migrations.RunPython(create_owner_memberships, remove_owner_memberships),
    ]
