# Generated by Django 6.0.2 on 2026-03-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0055_populate_owner_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmembership',
            name='welcomed',
            field=models.BooleanField(default=False, help_text='Has the user seen the welcome message?'),
        ),
    ]
