# Generated by Django 6.0.2 on 2026-03-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0056_add_welcomed_to_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmembership',
            name='notify_on_complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantmembership',
            name='notify_on_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantmembership',
            name='notify_on_non_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantmembership',
            name='notify_on_reservation',
            field=models.BooleanField(default=False),
        ),
    ]
