# Generated by Django 6.0.2 on 2026-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0058_mark_existing_owners_welcomed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantknowledgebase',
            name='valet_cost',
            field=models.TextField(blank=True, default=''),
        ),
    ]
