# Generated by Django 6.0.2 on 2026-03-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0059_kb_valet_cost_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='caller_sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('frustrated', 'Frustrated'), ('upset', 'Upset')], default='neutral', max_length=16),
        ),
    ]
