# Generated by Django 6.0.2 on 2026-03-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0060_calldetail_caller_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmembership',
            name='notify_email',
            field=models.EmailField(blank=True, default='', help_text='Override email for notifications. Falls back to user account email if blank.', max_length=254),
        ),
    ]
