# Generated by Django 6.0.2 on 2026-04-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0065_defective_call_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='retell_conversation_flow_id',
            field=models.CharField(blank=True, default='', help_text='Retell Conversation Flow ID. If set, the agent uses conversation-flow instead of retell-llm.', max_length=64),
        ),
    ]
