# Generated by Django 6.0.2 on 2026-04-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0068_subscription_sms_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='agent_name',
            field=models.CharField(blank=True, default='', help_text="Name the agent uses to introduce itself (e.g. 'Gaby'). Leave blank for no name.", max_length=100),
        ),
    ]
