# Generated by Django 6.0.2 on 2026-04-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0069_restaurant_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=8),
        ),
        migrations.AddField(
            model_name='smslog',
            name='from_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent (in transit)'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('received', 'Received')], default='pending', max_length=16),
        ),
    ]
