# Generated by Django 6.0.2 on 2026-05-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0070_smslog_direction_and_from_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='notify_on_sms_reply',
            field=models.BooleanField(default=True, help_text='Email the owner when a caller replies to an outbound SMS.'),
        ),
    ]
