# Generated by Django 6.0.2 on 2026-05-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0071_add_notify_on_sms_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='balance_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
