# Generated by Django 6.0.2 on 2026-05-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0072_subscription_balance_alert_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='balance_blocked_call_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
