# Generated by Django 6.0.2 on 2026-05-24 21:11

import django.db.models.deletion
import restaurants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0073_subscription_balance_blocked_call_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='notify_via_push',
            field=models.BooleanField(default=False, help_text='Master switch for browser push notifications.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, help_text='Resume push at this local time.', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='quiet_hours_skip_urgent',
            field=models.BooleanField(default=True, help_text='Always ring for complaints, even during quiet hours.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, help_text='Mute non-urgent push starting at this local time.', null=True),
        ),
        migrations.AddField(
            model_name='restaurantmembership',
            name='notify_via_push',
            field=models.BooleanField(default=False, help_text='Receive browser push notifications for this restaurant.'),
        ),
        migrations.CreateModel(
            name='CallActionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=restaurants.models._generate_call_action_token, max_length=64, unique=True)),
                ('action_type', models.CharField(choices=[('reservation', 'Reservation request'), ('complaint', 'Complaint'), ('followup', 'Follow-up needed'), ('non_customer', 'Business call')], max_length=16)),
                ('response', models.CharField(blank=True, choices=[('', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'No availability'), ('callback', 'Will call back'), ('resolved', 'Manually resolved')], default='', max_length=16)),
                ('response_note', models.CharField(blank=True, default='', help_text='Optional custom message from owner included in SMS.', max_length=500)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('edited_date', models.DateField(blank=True, null=True)),
                ('edited_time', models.TimeField(blank=True, null=True)),
                ('edited_party', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField(help_text='Default created_at + 24h.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_tokens', to='restaurants.calldetail')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_tokens', to='restaurants.restaurant')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'used_at', 'expires_at'], name='restaurants_restaur_1b9865_idx'), models.Index(fields=['used_at', 'expires_at'], name='restaurants_used_at_aa6bf2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=2048)),
                ('key_p256dh', models.CharField(max_length=200)),
                ('key_auth', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('label', models.CharField(blank=True, default='', help_text='Friendly device label shown in settings.', max_length=80)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant', 'user'], name='restaurants_restaur_48940c_idx')],
                'unique_together': {('user', 'restaurant', 'endpoint')},
            },
        ),
    ]
