# Generated by Django 6.0.2 on 2026-05-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0074_push_subscription_and_action_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='first_viewed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='calldetail',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('needs_reply', 'Needs reply'), ('resolved', 'Resolved')], db_index=True, default='new', help_text='Workflow state. Drives inbox tab bucketing and overdue banner.', max_length=16),
        ),
    ]
