# Generated by Django 6.0.2 on 2026-06-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0076_backfill_call_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('ip', models.GenericIPAddressField()),
                ('lang', models.CharField(default='en', max_length=4)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('retell_call_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('failed', 'Failed')], default='triggered', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vertical',
            field=models.CharField(choices=[('restaurant', 'Restaurant / Bar'), ('home_services', 'Home Services'), ('medical', 'Medical / Clinic'), ('real_estate', 'Real Estate'), ('beauty', 'Beauty & Wellness'), ('hotel', 'Hotel / Hospitality'), ('other', 'Other')], db_index=True, default='restaurant', help_text='Industry vertical — drives KB template and agent prompt.', max_length=32),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('vertical', models.CharField(choices=[('restaurant', 'Restaurant / Bar'), ('home_services', 'Home Services'), ('medical', 'Medical / Clinic'), ('real_estate', 'Real Estate'), ('beauty', 'Beauty & Wellness'), ('hotel', 'Hotel / Hospitality'), ('other', 'Other')], db_index=True, max_length=32)),
                ('lang', models.CharField(default='en', max_length=4)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False, help_text='True once we sent the launch email.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'vertical')},
            },
        ),
    ]
