# Generated by Django 6.0.2 on 2026-06-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0078_add_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='opentable_rid',
            field=models.CharField(blank=True, default='', help_text='OpenTable Restaurant ID (rid), e.g. 1274317 — builds the pre-filled booking link for self-serve mode.', max_length=32),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='reservation_mode',
            field=models.CharField(choices=[('capture', 'Capture details — the team confirms'), ('self_serve', 'Self-serve — text the caller a pre-filled OpenTable booking link')], default='capture', help_text="How the agent handles reservations. 'capture' = collect details, team confirms. 'self_serve' = text the caller a pre-filled OpenTable booking link.", max_length=16),
        ),
    ]
