# Generated by Django 6.0.2 on 2026-06-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0079_restaurantknowledgebase_opentable_rid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='regular_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
