# Generated by Django 6.0.2 on 2026-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0080_restaurantknowledgebase_regular_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='transfer_destinations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
