# Generated by Django 6.0.2 on 2026-06-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0081_restaurantknowledgebase_transfer_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='entertainment_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='special_events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
