# Generated by Django 6.0.2 on 2026-06-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0082_restaurantknowledgebase_entertainment_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='event_reminder_weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, help_text='Day of week the entertainment-refresh reminder is sent (restaurant timezone).'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notify_event_reminder',
            field=models.BooleanField(default=False, help_text='Weekly push + email reminder to refresh the entertainment & events schedule.'),
        ),
    ]
