# Generated by Django 6.0.2 on 2026-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0083_restaurant_event_reminder_weekday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='sms_templates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurantknowledgebase',
            name='sms_templates_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
